### ISSUE TITLE
Allow Script Execution Without Specifying `.py` Extensions

### ISSUE THREAD

**Issue by hackergandhi** [hackergandhi/LockBoxXtreme#11]
### Description:

Currently, the project requires the `.py` extension to be specified when executing the scripts (`encryption.py, storage.py, and main.py`). This can be improved for better usability by allowing the scripts to be executed directly by name, without needing to specify the `.py` extension.

### Proposed Changes:

**Rename Files:**

- Rename `encryption.py` to `encryption`
- Rename `storage.py` to `storage`
- Rename `main.py` to `main`

### Update Shebang:

- Add or update the shebang line in each script to `#!/usr/bin/env python3` to ensure they are recognized as Python scripts and can be executed directly.

### Update Imports (if necessary):

- Ensure that any internal imports in the `main` script (or other scripts) are updated to work without relying on the `.py` extension. Consider using `importlib` for dynamic imports if needed.

### Testing:

- Verify that all scripts can be executed directly by name in the terminal or command prompt without needing the .py extension.

- Ensure that the internal functionality and module imports remain unaffected by this change.

**Comment by gandhibhai** [comment]
check #[d9e1b6d] commit in encryption file

**Comment by i3hz** [comment]
Btw why'd you use json as storage , why not a different file format ? Just curious

**Comment by gandhibhai** [comment]
> Btw why'd you use json as storage , why not a different file format ? Just curious

Bro, the project is still in development, so it's not fixed that we'll stick with JSON. There wasn't any specific reason for choosing JSON; it was just convenient and easy to work with for now. But depending on future requirements, we might switch to a different format.

**Comment by i3hz** [comment]
Ah that makes sense , thanks

**Comment by Hackerjatti32** [comment]
kindly check 23f4997 and e42b3d3 and testing is pending for now

**Comment by Hackerjatti32** [comment]
Update Imports in `main` file:

Replace the import statements with code that dynamically loads the modules without using the `.py` extension

```python
#!/usr/bin/env python3

import sys
import os
import time
import colorama
from colorama import Fore, Style
import importlib.util
from getpass import getpass
import json
import shutil

sys.dont_write_bytecode = True

# Dynamically import the encryptor module
def load_module(module_name, module_path):
    spec = importlib.util.spec_from_file_location(module_name, module_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module

encryptor = load_module("encryptor", "encryptor")
storage = load_module("storage", "storage")

# Now you can use the functions from encryptor and storage
generate_key = encryptor.generate_key
load_key = encryptor.load_key
encrypt_message = encryptor.encrypt_message
decrypt_message = encryptor.decrypt_message
validate_password = encryptor.validate_password
save_passwords = storage.save_passwords
load_passwords = storage.load_passwords
delete_service = storage.delete_service

# Rest of your main.py code follows...
```
Check bec8fa2 commit

**Comment by Hackerjatti32** [comment]
[11eabcb](https://github.com/hackergandhi/LockBoxXtreme/commit/11eabcb856a72a02b96daa40798345b96053e69e)

**Comment by Hackerjatti32** [comment]
[4492dce](https://github.com/hackergandhi/LockBoxXtreme/commit/4492dce6aad925da57f41c0a5cc72ff408f42232)

**Comment by Hackerjatti32** [comment]
Hi @hackergandhi @i3hz 

Even after making changes in the file, I'm still getting this error: 

``` 
─# python3 main 
Traceback (most recent call last): 
  File "/home/gandhi/Desktop/Targets/LockBoxXtreme/main/main", line 27, in <module> 
    encryptor = load_module("encryptor", "./encryptor") 
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/home/gandhi/Desktop/Targets/LockBoxXtreme/main/main", line 21, in load_module 
    raise FileNotFoundError(f"Module '{module_name}' not found at '{module_path}'") 
FileNotFoundError: Module 'encryptor' not found at './encryptor' 
```

So for now, I've temporarily renamed `encryptor.py` and `storage.py`. If you have any solution, please share.

check this [4492dce](https://github.com/hackergandhi/LockBoxXtreme/commit/4492dce6aad925da57f41c0a5cc72ff408f42232) commit

**Comment by hackergandhi** [comment]
hi @i3hz I would be very happy if you could resolve this issue :))

**Comment by i3hz** [comment]
Well i'll try to , but as I said im not the greatest
Do you guys want the file as a exe or like just without the .py extension

**Comment by hackergandhi** [comment]
> Currently, the project requires the .py extension to be specified when executing the scripts (encryption.py, storage.py, and main.py). This can be improved for better usability by allowing the scripts to be executed directly by name, without needing to specify the .py extension.

without the `.py` extentsion

**Comment by Hackerjatti32** [comment]
> Well i'll try to , but as I said im not the greatest Do you guys want the file as a exe or like just without the .py extension

hi @hackergandhi and @i3hz 

tell me right if i write something wrong

The error I'am encountering suggests that the script is trying to load the `encryptor` module using a dynamic import or a similar method but is failing because it can't find the module at the specified path. This can happen if the script is still expecting the file to have a `.py` extension, or if the path is incorrect after renaming the files.

### Steps to Resolve the Issue:

   **1) Check the Load Path:**

     -   Make sure that the script is trying to load the `encryptor` module from the correct path. If I've renamed `encryptor.py` to just `encryptor`, the path might need to be updated in this `main` script.

     -   Update the `load_module` function or similar logic in the `main` script to reference the correct file. If the script expects a file with a `.py` extension, I can modify the function to account for the new file name.

    **Example:**

    ```python

def load_module(module_name, module_path):
    if not os.path.exists(module_path):
        raise FileNotFoundError(f"Module '{module_name}' not found at '{module_path}'")
    # Adjust this logic to handle the lack of .py extension
    spec = importlib.util.spec_from_file_location(module_name, module_path + ".py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module
```

If the `module_path` is now `./encryptor`, you'll need to make sure this function knows that it should look for `./encryptor` rather than `./encryptor.py`.

**2) Use an Absolute Path or Correct Relative Path:**

   - Ensure that the path to the module is correct relative to the location of the `main` script. If the `encryptor` file is in the same directory as `main`, `./encryptor` should be correct, but if it’s in another directory, I’ll need to adjust the path accordingly.

**3) Check the Import Logic:**

 -   If this script uses `importlib`, `imp`, or any other dynamic import mechanism, make sure it's capable of importing a file without the `.py` extension. Some import methods might expect a `.py` file by default.

### Example with `importlib`:

```python

import importlib.util
import os

def load_module(module_name, module_path):
    if not os.path.exists(module_path):
        raise FileNotFoundError(f"Module '{module_name}' not found at '{module_path}'")

    spec = importlib.util.spec_from_file_location(module_name, module_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module
```

Ensure that module_path does not add `.py` if the file has been renamed.

**4) Consider Keeping the .py Extension:

   - If this change is causing too many issues, you guys might want to reconsider removing the .py extension. Instead, you could make the scripts executable while keeping the .py extension, which allows for easier imports:

```bash
chmod +x encryption.py storage.py main.py
```

And you can run them as:

```bash
./encryption.py
```

This approach maintains compatibility with Python's module loading system

**Comment by i3hz** [comment]
Well it really depends on how important is removing the .py extension .
I don't know what advantages it gives for i've never tried it .
>The error I'am encountering suggests that the script is trying to load the encryptor module using a dynamic import or a similar method but is failing because it can't find the module at the specified path. This can happen if the script is still expecting the file to have a .py extension, or if the path is incorrect after renaming the files.

Yeah that most probably a reason we would either need to load it using a function of some sort as I tried with the absolute path thing and it didn't work

**Comment by hackergandhi** [comment]
hi @i3hz 

> Yeah that's most probably the reason, we would either need to load it using a function of some sort as I tried with the absolute path thing and it didn't work

No worries, bro. There's no need for the project to be used without the extension at this time. We'll try to address this in the future, so I'm closing this issue for now. If you're able to resolve it, please commit the changes in the code file, and reopen this issue, and report back to me
